### ISSUE TITLE
RED (not equals) and GREEN (ignored) areas are not shown at result image at the same time

### ISSUE THREAD

**Issue by mrgoroua** [romankh3/image-comparison#113]
Actual: 
if there are several ignored rectangles was set and test has been failed because of defferences in other places -> only RED areas are shown at result image

Expected: 
failed and ignored areas are shown simultaneously at result image

`@Test
    public void testNotEquals() throws IOException {

        File ExpectedCash = new File(".\\helperfiles\\receipts\\receipt1.png");
        File ActualCash = new File(".\\helperfiles\\receipts\\receipt2.png");
        File resultDestination = new File(".\\helperfiles\\receipts\\resultImage.png");

        BufferedImage image1 = readImageFromFile(ExpectedCash);
        BufferedImage image2 = readImageFromFile(ActualCash);
        List<Rectangle> excludedAreas = new ArrayList<>();
        //excludedAreas.add(new Rectangle(60, 384, 915, 515)); -------- shown AS RED on result picture
        excludedAreas.add(new Rectangle(385, 515, 915, 565));  //  -- not shown at result picture
        excludedAreas.add(new Rectangle(385, 630, 915, 750));   // -- not shown at result picture

        ImageComparison imageComparison = new ImageComparison(image1, image2);
        imageComparison.setExcludedAreas(excludedAreas);
        imageComparison.setRectangleLineWidth(5);

        imageComparison.setDrawExcludedRectangles(true);
        ComparisonResult result = imageComparison.compareImages().writeResultTo(resultDestination);
        assertEquals(result.getComparisonState(), MATCH);

    }`

// image 1
![receipt1](https://user-images.githubusercontent.com/14112575/58800166-d6ed0600-860f-11e9-95bc-14e79b7a1cca.png)

// image 2
![receipt2](https://user-images.githubusercontent.com/14112575/58800167-d7859c80-860f-11e9-8fca-929544278b38.png)

// result image
![resultImage](https://user-images.githubusercontent.com/14112575/58800168-d7859c80-860f-11e9-8710-26ac302c3832.png)

**Comment by romankh3** [comment]
@mrgoroua, added the fix for and published as `3.1.1` version.
Please, check and close the issue.

**Comment by mrgoroua** [comment]
fixed
