### ISSUE TITLE
[BUG] Can not compare "10" and "11" in two images

### ISSUE THREAD

**Issue by lbingyan** [romankh3/image-comparison#128]
**Describe the bug**
I have two images, and the first one fill out the age field as "10" while the second one is "11", but the comparison result is passed.

here is my code
`

    imageComparison.setThreshold(5);
    imageComparison.getThreshold();

    imageComparison.setRectangleLineWidth(2);
    imageComparison.getRectangleLineWidth();
    
    imageComparison.setPixelToleranceLevel(0.005);
    imageComparison.getPixelToleranceLevel();

    imageComparison.setDestination(resultDestination);
    imageComparison.getDestination();

    imageComparison.setMinimalRectangleSize(100);
    imageComparison.getMinimalRectangleSize();
`

**Comment by romankh3** [comment]
Hello, @lbingyan.
Please, provide test images which are reproduced in this case.

Best regards,
Roman.

**Comment by lbingyan** [comment]
> 
> 
> Hello, @lbingyan.
> Please, provide test images which are reproduced in this case.
> 
> Best regards,
> Roman.

Hi Roman, 

here are two images:

![8297a509-682c-41c9-883f-3ada44804ede_actual](https://user-images.githubusercontent.com/43946927/62751677-267c0200-ba97-11e9-80e6-c098170d7d9c.png)
![a3f690ee-84de-4218-a1bc-d684603cd547_excepted](https://user-images.githubusercontent.com/43946927/62751682-2c71e300-ba97-11e9-967a-27e3fa12416f.png)

**Comment by lbingyan** [comment]
I have a question, what does "MinimalRectangleSize" mean, the comparison minimal unit? I change the "imageComparison.setMinimalRectangleSize(100)" to "imageComparison.setMinimalRectangleSize(50);" and it works.

**Comment by romankh3** [comment]
`minimalRectangleSize` mean that the rectangles, which are fewer that this value - won't be counted in comparison.
Please, read it: https://github.com/romankh3/image-comparison#configurations

Best regards,
Roman.

**Comment by lbingyan** [comment]
> 
> 
> `minimalRectangleSize` means that the rectangles, which are fewer that this value - won't be counted in comparison.
> Please, read it: https://github.com/romankh3/image-comparison#configurations
> 
> Best regards,
> Roman.

Thanks.

**Comment by romankh3** [comment]
if you any suggestions to improve `image-comparison` - welcome.
For example. the description of the configurations can be not clear for newcomers  or something else.

Best regards,
Roman,
