### ISSUE TITLE
[BUG] Throwing an IllegalArgumentException: -1

### ISSUE THREAD

**Issue by aruna-rajapaksha-nzta** [romankh3/image-comparison#129]
**Describe the bug**
Exception in thread "main" java.lang.IllegalArgumentException: -1

**To Reproduce**
Steps to reproduce the behaviour:
1. Compare 2 images of the same size with differences using below version
<dependency>
      <groupId>com.github.romankh3</groupId>
      <artifactId>image-comparison</artifactId>
      <version>3.2.0</version>
    </dependency>

**Expected behaviour**
Output image with highlighted differences  

**Screenshots**
<img width="708" alt="Screen Shot 2019-08-16 at 6 07 50 AM" src="https://user-images.githubusercontent.com/44488903/63115929-7a816c00-bfec-11e9-8257-5a46b19c06d9.png">

**Comment by romankh3** [comment]
Hello, @aruna-rajapaksha-nzta!
Please, provide images with which can reproduce this bug.

Best regards,
Roman

**Comment by romankh3** [comment]
@aruna-rajapaksha-nzta , move it to backlog until you provide more details.
