### ISSUE TITLE
[BUG] If image is different in a line in 1 px, ComparisonState is always MATCH

### ISSUE THREAD

**Issue by grigaman** [romankh3/image-comparison#134]
In version 3.3.0 the is a problem in populateRectangles.
If in second image there is additional line in one pixels, populateRectangles will not add rectangle for this line to results.
For example:
* Image 1: 50x50 all pixels are white
* Image 2: 50x50, and have black line 5, 24 - 44, 24
populateRectangles in this case will try calculate size and will get value 0 because 24-24 = 0, but it should return 40*1, because minPoint and maxPoint are included.
Need to fix methods getWidth, getHeight in Rectangle on:
```
public int getWidth() {
  return maxPoint.getX() - minPoint.getX() + 1;
}
public int getHeight() {
  return maxPoint.getY() - minPoint.getY() + 1;
}
```

**Comment by romankh3** [comment]
Hi @grigaman, I've got your point!
It's really a bug. Thanks for your catch.
I'm worried that for all the cases it will be added an extra one.

**Comment by grigaman** [comment]
Also please look at my pool request which fix the issue.
About some imrovements:
At present the red rectangle is drawn over mismatched pixels (for example 1px line will change color to red one), may be it is better to change draw method and draw rectangle around rectangle of changes pixels. For example if border width is 1px, rectangle will be drawn on 1px before changed pixels: x-1, y-1, width - 1 + 1, height - 1 + 1

**Comment by romankh3** [comment]
I saw your changes and left feedback for them.

**Comment by romankh3** [comment]
@grigaman, thanks for your contribution!
