### ISSUE TITLE
[BUG] deepCopy method throws IllegalArgumentException on shared BufferedImage

### ISSUE THREAD

**Issue by grigaman** [romankh3/image-comparison#136]
If pass BufferedImage which is get from some BufferedImage operation (for example getSubimage), deepCopy method thrown IllegalArgumentException. Example of exception:
`java.lang.IllegalArgumentException: Raster ByteInterleavedRaster: width = 202 height = 20 #numDataElements 3 dataOff[0] = 2 has minX or minY not equal to zero: -1 -1`

To fix this issue need to pass into copyData `image.getRaster().createCompatibleWritableRaster()` instead of null

**Comment by romankh3** [comment]
Your contributing is amazing!
Where do you use `image-comparison`?

**Comment by romankh3** [comment]
Thanks for your contribution!
