### ISSUE TITLE
[IMPROVEMENT] Optimize the isDifferentPixels method

### ISSUE THREAD

**Issue by mw79** [romankh3/image-comparison#152]
isDifferentPixels method could be optimized. We could precalculate Math.pow(differenceConstant * pixelToleranceLevel, 2) and use this value in comparison with sum of squares of color distances. Whan we will use this method for comparison of thousands of pixels this would be more optimal.

**Comment by romankh3** [comment]
Good point, @mw79! 
Thanks for your catch.
Are you going to implement it?
