### ISSUE TITLE
Question: identical image detection with tolerance 

### ISSUE THREAD

**Issue by mboullouz** [romankh3/image-comparison#161]
Is there a  way to check if 2 images has some differences ? 
we would like to ignore alerting if is there few differences between 2 images.
something like bellow would do it ?
`boolean isSameImgsWith8Dot5PercentTolerance = imageComparisonResult.getDifferencePercent() <8.5 ; `
We are in the process of evaluating tools for our QA process,
Thank you for your help

**Comment by romankh3** [comment]
Hello @mboullouz. Thanks for your interest in `image-comparison`
Tell me please, What do you mean in `some differences`? 

`image-comparison` has many configurations for comparing, such as:
*  ignore areas from comparison
*  set minimal rectangle size for differences
*  set pixel tolerance level to pass or not almost the same pixels.
*  set maximal rectangle count

```
    /**
     * The number of the minimal rectangle size. Count as (width x height).
     */
    private Integer minimalRectangleSize = 1;

    /**
     * Maximal count of the {@link Rectangle}s.
     * It means that would get first x biggest rectangles.
     * Default value is -1, that means that all the rectagles would be drawn.
     */
    private Integer maximalRectangleCount = -1;

    /**
     * Level of the pixel tolerance. By default it's 0.1 -> 10% difference.
     * The value can be set from 0.0 to 0.99.
     */
    private double pixelToleranceLevel = 0.1;

```
 
Best regards,
Roman.

**Comment by romankh3** [comment]
@mboullouz, I close the issue.
If you have any other questions\suggestions - please, create a new issue.

Best regards,
Roman
