### ISSUE TITLE
[FEATURE] Create greyscale image before drawing rectangles

### ISSUE THREAD

**Issue by JohannBlake** [romankh3/image-comparison#163]
To make it easier to see all the rectangles, it would be nice if you could add a feature that firsts converts the image into a greyscale and possibly even apply an alpha to make the image slightly transparent. When you draw the red rectangles on top of this greyscale, it will be very easy to quickly locate the rectangles.

**Comment by romankh3** [comment]
Hi, @JohannBlake.
Is it useful for someone? I want you to understand, that the existing flow of comparing would be changed.

Best regards,
Roman.

**Comment by MrMisterG** [comment]
Just my 2 cents @JohannBlake 
- Workaround: Increase rectangleLineWidth. (I think I set 3 or 4 here and like the results)
- Additional or alternative idea: Configure square colours (default stays red).
:)
Stuart

**Comment by romankh3** [comment]
@JohannBlake, I close the issue.
If you have any questions\suggestions - create a new issue.

Best regards,
Roman.
