### ISSUE TITLE
Exception when maximalRectangleCount is bigger than rectangles.size() [BUG]

### ISSUE THREAD

**Issue by Hexronimo** [romankh3/image-comparison#165]
When you set some wanted number of rectangles with `imageComparison.setMaximalRectangleCount(10);` (other then -1) and the comparing found fewer rectangles than this number, you got java.lang.IllegalArgumentException: -3 at 
ImageComparison.java:359 because in

           ` rectanglesForDraw = rectangles.stream()

                    .sorted(Comparator.comparing(Rectangle::size))

                    .skip(rectangles.size()-maximalRectangleCount)

                    .collect(Collectors.toList());`

_rectangles.size()-maximalRectangleCount_ will be negative number.

**Comment by romankh3** [comment]
@Hexronimo, thanks for your catch. The bug will be published ASAP.

Best regards,
Roman.

**Comment by romankh3** [comment]
the new release has been published.
