### ISSUE TITLE
[IMPROVEMENT] fill excluded rectangles with transparent green

### ISSUE THREAD

**Issue by MrMisterG** [romankh3/image-comparison#167]
I add many excluded areas to my images and find it very useful that they appear as green rectangles on the results image.
I often need to define long exclusions along edges of the image. In those cases, looking at the resulting image, it is not easy to determine which areas have been excluded, partly due to the fact that the green lines along the edges are cropped out of the picture.

It would be less ambiguous if there was an option to fill the the green rectangles with a transparent green fill.

**Comment by romankh3** [comment]
Hi, @MrMisterG.
I think, that this is a good idea and it can be added to `image-comparison`.
For this time, I don't have enough time to do it. Due to this fact, I can suggest you do it if you want it. 
We can discuss the details of the implementation here.

Best regards,
Roman.

**Comment by romankh3** [comment]
All the changes must be backward-compatible with previous versions. 

So we can add method with these configurations(boolean fillFullRectangle, double persentOfOpaque)

I think, that the colors must stay as-is. 

These changes can be applied to the main rectangles, too.

**Comment by MrMisterG** [comment]
Hello @romankh3 
So far I have written the new setter method `setRectangleProperties(Boolean fillRectangles, Double percentOpacity)`
Ok like this?
Also, do you also expect getters for the new configuration properties?
BR
Stuart

**Comment by romankh3** [comment]
Hello @MrMisterG 
We need to create at least two methods for excluded and difference rectangles.

like it:
* `setExcludedRectangleFilling(boolean fillRectangles, double percentOpacity)` - add cofigurations for excluded areas(reactangles)
* `setRectangleFilling(boolean fillRectangles, double percentOpacity)` - add configuration for the rectangles of the differences.

BR
Roman

**Comment by MrMisterG** [comment]
Hi @romankh3 
I created a pull request... It is my first one to GitHub so I hope I did it correctly.
Please let me know if there is any issue.
BR
Stuart

**Comment by romankh3** [comment]
Hi @MrMisterG 
I saw Pull-Request. You did very well!
I added minor comment, please, resolve it.

BR
Roman

**Comment by MrMisterG** [comment]
Thanks! :) I updated it

**Comment by romankh3** [comment]
@MrMisterG Thanks for your contributions!
