### ISSUE TITLE
[QUESTION]comparing images made on different laptops with different resolutions

### ISSUE THREAD

**Issue by jeffradom** [romankh3/image-comparison#181]
Hello Roman,

Let's say we use Selenium/Java/Chrome to create baseline images on a 15-inch Macbook and create actual Chrome pages screenshots on 13-inch Macbook.  So, even I set browser size the same for example 1024x768 on both images/both laptops look a different size.  Can you please, suggest any possible workaround?

Thanks a lot in advance

Jeff

**Comment by romankh3** [comment]
Hello Jeff.
As far as I remember 13" and 15" have different sizes, so screenshots would be with different sizes.
this library doesn't support the ability to compare images with different sizes.

Does MacBook support the same screen resolution for 13" and 15"?

Best regards,
Roman
