### ISSUE TITLE
problem measuring exclusion areas 

### ISSUE THREAD

**Issue by jradom** [romankh3/image-comparison#187]
Hi Roman,

I'm trying to define several exclusion areas on Mac using some third-party tools but always miss and use trial and error method.  Or your calculations are somehow depending on resolution, etc.  I can still do it but it's a very time-consuming process.  Can you suggest a good and easy way to get coordinates using Mac?  I also plan to move my tests to Jenkins where I have no idea how to get successful coordinates using what tool?  Resolution there will be different from a local.  I use Selenium Screenshots to create images and, then compare them.

Thanks a lot in advance

Jeff

**Comment by romankh3** [comment]
Hi @jradom.
I'm not sure, that I can help you due to several reasons. I'm not a professional mac user...
If you find the solution - please share it here.

Best regards,
Roman.

**Comment by romankh3** [comment]
@jradom if you have ideas, please open a new issue with it.
