### ISSUE TITLE
[IMPROVEMENT] Include rectangles with difference in comparison results

### ISSUE THREAD

**Issue by akondas** [romankh3/image-comparison#192]
I propose to add to the results of the comparison the coordinates of the rectangles that differ (have been detected). I have already made the proposed code changes that will be in the PR.

**Comment by romankh3** [comment]
Hi @akondas,
Could you please provide cases in which you think that this is really needed?

**Comment by akondas** [comment]
For example: after performing the first comparison, I would like to suggest to the user that the selected fields should be replaced with the excluded ones (he could choose which ones to stay and which not to). Another example is the collection of this data for statistical purposes.

**Comment by romankh3** [comment]
Ok, I will add it to the next release. Please, create a new pr to `development` branch.

**Comment by romankh3** [comment]
merged to development branch and will added to next release,

**Comment by akondas** [comment]
Thanks :beers:

**Comment by romankh3** [comment]
@akondas, added in `4.3.0` version. It takes some time to publish to MavenCentral and jCenter.
