### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by dee-y** [romankh3/image-comparison#20]
Hello @romankh3, i am a graphic designer. I would like to know if you would be interested in me making a logo for this project. If you would have me, i would make a logo for you, and it's free.

**Comment by romankh3** [comment]
Hello, @dee-y.
It's an interesting proposal for my project, the logo can make it better. 
But I didn't get, why do you want to do it?

**Comment by dee-y** [comment]
Lolz oh, just cause i love contributing to open source projects. Kind of a
life goals thing...

**Comment by dee-y** [comment]
Hi @romankh3, i came up with these two ideas, do you like any of them? other ideas are also welcomed...
![image comparison-01](https://user-images.githubusercontent.com/36637989/41949799-da405f9e-79ba-11e8-8cd4-0af3ac36567e.jpg)

**Comment by dee-y** [comment]
i tried to present the comparison indicator with the red outline in the first logo, then the "I" and "C" inside for image comparison.

**Comment by romankh3** [comment]
Hi, @dee-y !
I like the second logo. 
<img width="470" alt="2018-06-27 7 12 01" src="https://user-images.githubusercontent.com/16310793/41952689-f008b622-79d9-11e8-8907-0232624fbf45.png">

**Comment by romankh3** [comment]
Also, I have the idea to put something changes into the red rectangle. Two images near and red rectangle, which show the difference.
what do you think about it?

**Comment by romankh3** [comment]
@dee-y, the last logo looks very-very good. I like it! 
Maybe little mark with the size of the rectangle. I think size could be smaller. What do you think? 
<img width="343" alt="2018-06-27 11 26 55" src="https://user-images.githubusercontent.com/16310793/41962196-1375c82a-79fd-11e8-8791-54c18244e4b9.png">

**Comment by dee-y** [comment]
Hello @romankh3 i have adjusted the rectangle here


![image comparison 1](https://user-images.githubusercontent.com/36637989/41973027-a965090a-7a0b-11e8-922b-0fb4b4e47eb8.jpg)

Do i have the go ahead to make a pull request with the transparent version? as well as export all necessary editable formats for you?

**Comment by romankh3** [comment]
@dee-y, Yes, You do.

**Comment by dee-y** [comment]
Hello @romankh3, i have created the pull request on here https://github.com/romankh3/image-comparison/pull/22

you can download the full editable versions of the logo files here from google drive link https://drive.google.com/drive/folders/1ATotqeduNWTT4mDRHBPnh21XVJQ9KRlh?usp=sharing

i also created a favicon version of the logo which is attached to the pull request in case you might need it. 

Here is my email if you need any future assistance 
stevetech2012@gmail.com

best regards,
Dee-y.

**Comment by romankh3** [comment]
Hello, @dee-y !
You've done great work!
Thank you for your time.

**Comment by romankh3** [comment]
Logos've added to the project.
