### ISSUE TITLE
[QUESTION] how to tell if the comparison has no difference? 

### ISSUE THREAD

**Issue by igorgiumellizup** [romankh3/image-comparison#200]
Hey Roman Beskrovnyi,
how can I tell if after ```//After configuring the ImageComparison object, can be executed compare() method:
        val imageComparisonResult: ImageComparisonResult = imageComparison.compareImages()``` no difference was found? I only want to generate the result file when there is difference. And also for assertions matter, the code needs to know if there is any difference found. I din't find any info about it in the git hub redame. 
Thanks!

**Comment by romankh3** [comment]
Hello, @igorgiumellizup.
Thanks for your interest in `image-comparison`.
I know, that the `README` may be better :)
For a better understanding of how `image-comparison` works, you can see the tests for it.
For example one of them:
```
@DisplayName("Should perform maximal rectangle count")
    @Test
    public void shouldPerformMaximalRectangleCount() {
        //given
        ImageComparison imageComparison = new ImageComparison("expected.png", "actual.png");
        imageComparison.setMaximalRectangleCount(3);
        BufferedImage expectedImage = readImageFromResources("maximalRectangleCountResult.png");

        //when
        ImageComparisonResult imageComparisonResult = imageComparison.compareImages();

        //then
        assertEquals(MISMATCH, imageComparisonResult.getImageComparisonState());
        assertImagesEqual(expectedImage, imageComparisonResult.getResult());
    }
```

it's a usual test, which checks [`ImageComparisonResult`](https://github.com/romankh3/image-comparison/blob/master/src/main/java/com/github/romankh3/image/comparison/model/ImageComparisonResult.java).

I hope, it will help you.

Best regards,
Roman B.

**Comment by igorgiumellizup** [comment]
What's the API behind 'assertImagesEqual' ?
It would be more efficient not to create the resulting image when there's no difference

**Comment by romankh3** [comment]
`assertImagesEqual` just a private method in the test class.

It's not created a new result image in the case when they match. Just take one of them.

**Comment by igorgiumellizup** [comment]
I noticed imageComparisonResult.getImageComparisonState() always returns MISMATCH regards if there's diference or not
