### ISSUE TITLE
[IMPROVEMENT] Compare images without size comparing or draw diff rectangles for images with diff size

### ISSUE THREAD

**Issue by Bohdan-Khylia** [romankh3/image-comparison#203]
Hi Roman,
I have a problem with comparing images that have a little size mismatch. In that case I receive diff image equal to actual and without diff rectangles, but 2 images have a lot of mismatches. Can you add improvement with one more method of comparing images without size comparing or improve exist method with drawing diff rectangles for images, that have size mismatch?

**Comment by romankh3** [comment]
Hi @Bohdan-Khylia.
By this time, `image-comparison` has a configuration about rectangle size, line size. Please, read more in README.md.

If it won't help you - provide images with examples, I will check it.

**Comment by Bohdan-Khylia** [comment]
I have 2 images: _actual_ and _expected_, this images have a little difference in width and if process of comparing this 2 images, rectangles are not adding to the result diff image, because of logic of the compare method.
![ac_constructor_text_field_advanced_panel_visual_screen](https://user-images.githubusercontent.com/61683509/111654825-c7a17180-8811-11eb-8928-944ff7fc541b.png)
![ex_constructor_text_field_advanced_panel_visual_screen](https://user-images.githubusercontent.com/61683509/111654850-cc662580-8811-11eb-8e66-1837923fb635.png)

**Comment by romankh3** [comment]
Unfortunately in this case you can not use it. The basic requirement for using image-comparison is to provide two images with the same width and height. Preparing images requires by library client.

**Comment by Bohdan-Khylia** [comment]
I have found workaround. I make resize for actual image, if it has different size than expected and after compare 2 images.

**Comment by romankh3** [comment]
From my side it’s not a workaround. It’s a requirements before comparing images. 

It’s good that you’ve found a solution for you.
