### ISSUE TITLE
StackOverflowError when compared 2 images with a little big different area.

### ISSUE THREAD

**Issue by alexbai326** [romankh3/image-comparison#21]
Hello @romankh3 
I got a Exception:
`Exception in thread "main" java.lang.StackOverflowError
	at ua.comparison.image.ImageComparison.joinToRegion(ImageComparison.java:110)`
when compared 2 images with a little big different area.
 Image resolution of both are : 1920 * 931, 
as attached 
image1:
![baidu1](https://user-images.githubusercontent.com/25541267/41827666-2784a8e0-7863-11e8-9c83-fbb0425a827c.png)
image2:
![baidu2](https://user-images.githubusercontent.com/25541267/41827667-27fecb52-7863-11e8-8e4c-8767c782bc6b.png)

**Comment by romankh3** [comment]
I saw this exception. the issue was closed (#17). 
I'll check it again.

**Comment by romankh3** [comment]
@alexbai326, Could you please provide original images? Sizes of these provided images are different. (30kb and 150 kb).

**Comment by alexbai326** [comment]
sorry for the previous images are compressed
image1:
![baidu1](https://user-images.githubusercontent.com/25541267/41832693-9c860910-787f-11e8-999b-38981e714ebe.png)
image2:
![baidu2](https://user-images.githubusercontent.com/25541267/41832707-ac4470a8-787f-11e8-9051-973acf7d1e65.png)

**Comment by romankh3** [comment]
@alexbai326, I've got the same as you. I'll see. I think it could be something with `bit color`. 
Image1 has 32-bit color.
Image2 has 24-bit color.
I thought I fixed it in #17. Need to think about it.
Also, these images the same sizes as they were before(30kb and 150 kb).

You're free to provide your own solution if you have it.
At the same time, I'll see what I can do.

**Comment by alexbai326** [comment]
Both are original images. Image2 was edited base on image1.
And their resolution  are the same: 1920 * 931.
![compare](https://user-images.githubusercontent.com/25541267/41832974-0b0f9030-7881-11e8-974e-562ec153b1bf.png)

**Comment by romankh3** [comment]
In my test images, which I'm using, sizes very similar(57.35Kb and 57.97Kb).
For the first time try to avoid changing sizes. 

I will see this example.

**Comment by kremenec** [comment]
I've got the same as @alexbai326 mention.

**Comment by gao2q** [comment]
me too. the same bug.

**Comment by pvarenik** [comment]
@romankh3 maybe in future, I haven't enough time now.

**Comment by romankh3** [comment]
@pvarenik, I see, it's a good reason, I closed your PR as not completed and worried about it.
Have a nice day.

**Comment by Markaleth** [comment]
Issue is still occurring. Any news?

**Comment by romankh3** [comment]
@Markaleth, hello. 
The issue still open. Week ago I started to do with the project again, so I want to do it. 
This issue has a high priority. It should be researched. If you have some ideas - welcome.

**Comment by pvarenik** [comment]
I created a PR for it https://github.com/romankh3/image-comparison/pull/28
but there should be added tests. The main sense of the bug that we check every pixel around the current check point. We should check only points that will be checked after current.
now:
```
check | check | check 
check |    *      | check  
check | check | check 
```
after
```
      -   |     -     |     -   
      -   |    *      | check  
check | check | check 
```

**Comment by romankh3** [comment]
@pvarenik, #28 was closed because of the reason, that it wasn't ready for merging. It should have prepared.

**Comment by romankh3** [comment]
@pvarenik thank you for an idea of the problem.
@alexbai326, @Markaleth issue has successfully resolved.
