### ISSUE TITLE
Diff saving destination is incorrect

### ISSUE THREAD

**Issue by pvarenik** [romankh3/image-comparison#25]
Hi, there is a mistake in _compareImages_ method (https://github.com/romankh3/image-comparison/blob/master/src/main/java/ua/comparison/image/ImageComparison.java#L120)

saveImage(Files.createTempFile("image-comparison", ".png" ).toFile(), outImg );

but should be something like

saveImage(this.destination, outImg );

**Comment by pvarenik** [comment]
I've created PR https://github.com/romankh3/image-comparison/pull/26

**Comment by romankh3** [comment]
Hi, @pvarenik.
Feel free to make changes and offer them via Pull-Request.

**Comment by romankh3** [comment]
Merged changes.
