### ISSUE TITLE
comparImage method is not visible

### ISSUE THREAD

**Issue by apathan123** [romankh3/image-comparison#30]
Hi,

I was going through the codebase and noticed that the below method
      _ImageComparison.compareImages() throws IOException_
is not exposed as public. Is there a specific reason. As per the code example, this may not work

_class Example {
    public static void main( String[] args ) {
        // load the images to be compared
        BufferedImage image1 = ImageIO.read( new File( "image1.png" )  );
        BufferedImage image2 = ImageIO.read( new File( "image2.png" )  );
        
        // where to save the result (leave null if you want to see the result in the UI)
        File result = new File( "result.png" );
        
        // compare them
        BufferedImage drawnDifferences = new ImageComparison( image1, image2, result).compareImages();
    }
}_

Error observed on running the code is --
_The method compareImages() from the type ImageComparison is not visible_

**Comment by romankh3** [comment]
I left this issue in my notifications.  I’ll see as soon as it possible. I don’t see any reasons to stay it private.  
By the way, if you want you can create PR for thi purpose. Contributing allows.

**Comment by romankh3** [comment]
@apathan123 thanks for your attention.
Updated access to `public`.
