### ISSUE TITLE
[IMPROVEMENT] Use it in a JUnitTest - And generate a ComparisonResult instead of Images

### ISSUE THREAD

**Issue by TobseF** [romankh3/image-comparison#62]
I wanted to compare a generated image with an approved one in a **JUnit test**. So if the images are equal we do not need to generate any files - because we already know they match. Only on a image mismatch I wan't to see my comparison image. In addition on big images with many changes, I need to ensure the time and memory consumption doesn't stress my test pipeline.

For this behavior I had to change your API a little bit:
* `compareImages()` Returns a `ComparisonResult` which holds the rectangles and a `CheckResult` state (ImageSizeMissmatch, Match, ImageMissmatch). So we can check the result and generate the images only if needed.
* `getImageComparison(int maximalDifferences)`: To speed up rendering we can limit the drawn recatngles. Before they were sorted by their size, so we can see the biggest differences.
* `writeImageComparison(File destination, int maximalDifferences)` which writes the comparison result to a file.
* A `minimumRectangleSize` field, which helps to prevent drawing very small rectangles.

I already forked yours and implemented these changes here: 
https://github.com/TobseF/image-comparison

Do you also want't to support such an usage? Then I could add your lib in as dependency, and don't need a complete fork.

**Comment by romankh3** [comment]
Hello, @TobseF.
I understand your needs. 

I like the ideas of adding `ComparisonResult`, `maximalDifferences' and `minimumRectangleSize`.

Let's talk more about the implementation of these ideas. My point is to save previous behavior.

`maximalDifferences` and `minimumRectangleSize` can be added as a configuration parameters for `ImageComparison` class the same as `threshold` variable.

changes in [fork](https://github.com/TobseF/image-comparison) without backward compatibility.

The API of the project isn't final and can be changed.

Best regards,
Roman.

**Comment by romankh3** [comment]
@TobseF, What do you think about it? You haven't answered yet.

Best regards,
Roman.

**Comment by romankh3** [comment]
I decided to implement your ideas.

Thank you @TobseF for a good idea of the usage `image-comparison`.
Stay tuned on 2.2.0-Release project. I will create related issues and will do it asap.

Best regards,
Roman.

**Comment by romankh3** [comment]
Implementation moved to 3.3.0 version.
