### ISSUE TITLE
[IMPROVEMENT] Deploy it to MAVEN

### ISSUE THREAD

**Issue by TobseF** [romankh3/image-comparison#63]
To use this lib, it would be very handy to include it via Maven. Do you plan to release your lib in Maven?

**Comment by romankh3** [comment]
Hello, @TobseF. I have an issue(#33) related to it.
If you have time, feel free to contribute it.
Notice, that all the services related to code quality must work as expected(travis-ci, coverall, etc).
Please, see the comments in #33.
This is duplicate.

**Comment by romankh3** [comment]
@TobseF, publishing added, you can use `2.1.0` version. See the barge in README.
