### ISSUE TITLE
Add ignored area highlighting

### ISSUE THREAD

**Issue by mrgoroua** [romankh3/image-comparison#97]
When user get coordinates and specifies plenty ignored regions there is not clear how to understnad whether coordinates was correct, or somethnig wrong with an app or code.

So that ignored areas highlightning at result picture would be a good idea to get it as one more investigation tool and understand that user's ignored rectangle's coordinates was correct and app correctly read them

**Comment by romankh3** [comment]
it's a good idea. I'll think about it.

**Comment by romankh3** [comment]
added in #104. Will be available in `3.1.0` version.
