### ISSUE TITLE
[BUG] Ignored area was not actually ignored

### ISSUE THREAD

**Issue by mrgoroua** [romankh3/image-comparison#98]
Ignored area was set at rectangle List but at the result image selected area was not excluded from comparison 
[see image](https://pasteboard.co/IgZ6Sa7.png)

`@Test
    public void testNotEquals() throws IOException {
        File resultDestination = new File( "C:\\!automation\\git\\ehopperDevUI\\helperfiles\\receipts\\resultImage.png");

        File ExpectedCash = new File("C:\\!automation\\git\\ehopperDevUI\\helperfiles\\receipts\\ExpectedCash.png");
        File ActualCash = new File("C:\\!automation\\git\\ehopperDevUI\\helperfiles\\receipts\\ActualCash.png");        

        //given
        BufferedImage image1 = readImageFromFile(ExpectedCash);
        BufferedImage image2 = readImageFromFile(ActualCash);
        List<Rectangle> excludedAreas = new ArrayList<>();

        excludedAreas.add(new Rectangle(80, 388, 900, 514));
        excludedAreas.add(new Rectangle(410, 514, 900, 565));
        excludedAreas.add(new Rectangle(410, 636, 900, 754));

        ImageComparison imageComparison = new ImageComparison(image1, image2);
        imageComparison.setExcludedAreas(excludedAreas);

        //when
        ComparisonResult result = imageComparison.compareImages();

        //And Result Image
        BufferedImage resultImage = result.getResult();

        //Image can be saved after comparison, using ImageComparisonUtil.
        ImageComparisonUtil.saveImage(resultDestination, resultImage);

        //then
        assertEquals(result.getComparisonState(), MATCH);

    }`

**Comment by romankh3** [comment]
@mrgoroua, please, provide image1 and image2 as files to reproduce it.
You can share it here, in issue or comments.

**Comment by mrgoroua** [comment]
![ActualCash](https://user-images.githubusercontent.com/14112575/58621263-a5073700-82d1-11e9-989f-1b8c01024c74.png)
![ExpectedCash](https://user-images.githubusercontent.com/14112575/58621264-a59fcd80-82d1-11e9-873a-193c4fcaf6cf.png)

**Comment by mrgoroua** [comment]
> @mrgoroua, please, provide image1 and image2 as files to reproduce it.
> You can share it here, in issue or comments.

Roman was it helpful?

**Comment by romankh3** [comment]
@mrgoroua I'm working on it.

**Comment by mrgoroua** [comment]
Fixed
