### ISSUE TITLE
Add usability to getMask[IMPROVEMENT]

### ISSUE THREAD

**Issue by mkytolai** [romankh3/image-comparison#99]
Currently getMask only returns a single rectangle, it ignores nested rectangles.
I have an idea on how to expand the method, will probably submit it later today

**Comment by romankh3** [comment]
Hello, @mkytolai.
Have you seen this issue? (https://github.com/romankh3/image-comparison/issues/98)
it's the first feedback from the real user about excluded areas.

**Comment by romankh3** [comment]
it's duplicate of #95, is it?
If yes, please close this issue and comment in #95 .

**Comment by romankh3** [comment]
@mkytolai, please follow #95.
